# =============================================================================
# docker-compose.yml - ODROID-HC4 Media Center containers
# Generated by setup.sh - do not edit directly; modify the template instead.
# =============================================================================

services:

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: Transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ${DOCKER_CONFIG_DIR}/Transmission:/config
      - ${DOCKER_CONFIG_DIR}/Transmission/watch:/watch
      - /media/torrents:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: Prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "9696:9696"
    volumes:
      - ${DOCKER_CONFIG_DIR}/Prowlarr:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: Sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "8989:8989"
    volumes:
      - ${DOCKER_CONFIG_DIR}/Sonarr:/config
      - /media/media/tv:/tv
      - /media/torrents:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "7878:7878"
    volumes:
      - ${DOCKER_CONFIG_DIR}/Radarr:/config
      - /media/media/movies:/movies
      - /media/torrents:/downloads
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: Jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "8096:8096"
      - "7359:7359/udp"
      - "1900:1900/udp"
    volumes:
      - ${DOCKER_CONFIG_DIR}/Jellyfin:/config
      - /media/media/tv:/data/TVShows
      - /media/media/movies:/data/Movies
    restart: unless-stopped

   byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: Byparr
    ports:
      - "8191:8191"
    environment:
      - HOST=0.0.0.0
      - PORT=8191
    restart: unless-stopped
